[SYNC-153][FE] Usability test fixes and improvements
NCTU-SYNC/sync-frontend pull request #50
Opened 2022-03-13 15:21 UTC by andyrochi

## Description: 
- Various updates and improvements based on feedbacks from usability test
- UI and flow updates in edit page (link and citation modal)
## Changes:
### Usability test updates and fixes

- [SYNC-155] Block users from submitting articles if any block is empty
- [SYNC-156] Fixed "Invalid time" bug in reading (`Article.vue`) page
- [SYNC-157][SYNC-158][SYNC-175][SYNC-176] Add an option for users to enable/disable date/time for a block
- [SYNC-159] Imported news will be inserted right behind the caret postion in the editor
- [SYNC-161] In the *import news panel* on the right side, search results will not be cleared when panel is closed
- [SYNC-163] Implemented content cache mechanism, the entire flow can be viewed [here](https://hackmd.io/@andycch/HJ79Vlbe5)
- [SYNC-179] Performance improvement and refactorization of edit page modals
- [SYNC-182] Show images in home page
- [SYNC-184] Validate links in link modal
### Feature updates
- [SYNC-165][SYNC-178] Updated link flow and show bubble menu when link clicked
## Test Scope:
- Post.vue
- Article.vue
- Home.vue
## Screenshots (optional)
- Enable/disable time option in datetime selector
![image](https://user-images.githubusercontent.com/39425103/158066439-79157e97-9d3e-43c5-8402-7c901794fcc5.png)
- Content cache
![image](https://user-images.githubusercontent.com/39425103/158066542-e013b3df-da5b-4cef-b8db-1edae50f4d14.png)
![image](https://user-images.githubusercontent.com/39425103/158066565-22628609-a902-460c-9969-73c623c480f3.png)
- Show images at the home page
![image](https://user-images.githubusercontent.com/39425103/158066582-d9490623-b423-48bd-86ef-05d386c939a1.png)
![image](https://user-images.githubusercontent.com/39425103/158066619-0abd5918-030d-4482-8f4a-9ef48ce287d7.png)
- Validate links in modal
![image](https://user-images.githubusercontent.com/39425103/158066669-58803b08-ed2d-4164-9971-de5533f38b24.png)
![image](https://user-images.githubusercontent.com/39425103/158066684-2ca27931-749c-4387-9c39-c616ea2764d3.png)
- New link flow
![image](https://user-images.githubusercontent.com/39425103/158066704-eda1a6d6-fdbd-49f3-b556-6374fd326620.png)

2022-03-14 13:13 UTC, jinan-tw approved these changes

2022-03-25 18:40 UTC, newb1er requested changes
code readability improvement.

2022-03-25 18:40 UTC, newb1er commented on src/components/Post/NavBarPost.vue
> +        await this.$bvModal.msgBoxOk('段落內文不得為空白，請輸入段落內文')
Iteration can be replaced by Array.prototype.every()
```suggestion
      if (Object.values(this.post.currentEditors).every((editor) => !editor.isEmpty))) {
        await this.$bvModal.msgBoxOk('段落內文不得為空白，請輸入段落內文')
      }
```

2022-03-25 18:40 UTC, newb1er commented on src/utils/index.js
> +  }
```suggestion
  for (const key of Object.keys(blocks)) {
    if (typeof blocks[key] === 'object') {
      getArticleImages(blocks[key], result, limit)
      if (result.imgLinks.length >= limit) {
        return
      }
    }
  }
```

2022-04-11 11:41 UTC, merged